#!/bin/bash

# Uncomment to Load all monitors
# ~/.config/openbox/monitors.sh

# Load a background image
feh --bg-fill ~/.config/openbox/background.jpg

# Load the compositor
xcompmgr &

# Load the taskbar and tray icons
tint2 &
nm-applet &
volumeicon &
cbatticon &
ibus-daemon -drx &
bitwarden &

# Load the policykit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &