#!/bin/bash

# Uncomment to Load all monitors
# ~/.config/openbox/monitors.sh

# Load a background image
feh --bg-fill ~/.config/openbox/background.jpg

# Load the compositor
picom -i 0.85 --active-opacity 0.9 &

# Load the taskbar and tray icons
tint2 &
nm-applet &
volumeicon &
cbatticon &
ibus-daemon -drx &
bitwarden &